function submit(){
    var user = document.getElementById("user")
    document.writeln("ADMISSION YEAR: " + document.myForm.user)
    console.log(user.value)
    var name = document.getElementById("name")
    document.write("<br>")
    document.writeln("FIRST NAME: " + document.myForm)
    var fname = document.getElementById("fname")
    document.write("<br>")
    document.writeln("NATIONALITY: " + document.myForm)
    var nation = document.getElementById("nation")
    document.write("<br>")
    document.writeln("RELIGION: " + document.myForm)
    var religion = document.getElementById("religion")
    document.write("<br>")
    document.writeln("CNIC: " + document.myForm)
    var CNIC = document.getElementById("CNIC")
    document.write("<br>")
    document.writeln("ADDRESS: " + document.myForm)
    var address = document.getElementById("address")
    document.write("<br>")
    document.writeln("GENDER: " + document.myForm)
    var gender = document.getElementById("gender")
    document.write("<br>")
    document.writeln("MARK OF IDENTIFICATION: " + document.myForm)
    var MOI = document.getElementById("MOI")
    document.write("<br>")
    document.writeln("CONTACT: " + document.myForm)
    var MOI = document.getElementById("CONATCT")
    document.write("<br>")
    document.writeln("POST CODE: " + document.myForm)
    var MOI = document.getElementById("POST CODE: ")
    document.write("<br>")
    document.writeln("BOARD / EXAMINATION BODY: " + document.myForm)
    var MOI = document.getElementById("BOARD / EXAMINATION BODY: ")
    document.write("<br>")
    document.writeln("GROUP: " + document.myForm)
    var MOI = document.getElementById("GROUP: ")
    document.write("<br>")
    document.writeln("ROLL NO.: " + document.myForm)
    var MOI = document.getElementById("ROLL NO.: ")
    document.write("<br>")
    document.writeln("GRADE + MARKS: " + document.myForm)
    var MOI = document.getElementById("GRADE + MARKS: ")
    document.write("<br>")
    document.writeln("BOARD / EXAMINATION BODY: " + document.myForm)
    var MOI = document.getElementById("BOARD / EXAMINATION BODY: ")
    document.write("<br>")
    document.writeln("GROUP: " + document.myForm)
    var MOI = document.getElementById("GROUP: ")
    document.write("<br>")
    document.writeln("ROLL NO : " + document.myForm)
    var MOI = document.getElementById("ROLL NO: ")
    document.write("<br>")
    document.writeln("GRADE + MARKS: " + document.myForm)
    var MOI = document.getElementById("GRADE + MARKS: ")
    document.writeln("SUBJECTS: " + document.myForm)
    var MOI = document.getElementById("SUBJECTS: ")

}